"""add job type to job table

Revision ID: 0ae530f56734
Revises: 6c1ac4325d72
Create Date: 2026-03-01 22:54:07.361806

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ae530f56734"
down_revision: Union[str, Sequence[str], None] = "6c1ac4325d72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs",
        sa.Column(
            "job_type",
            sa.Enum(
                "parsing", "reconciliation", name="job_type_enum", native_enum=False
            ),
            nullable=False,
        ),
    )
    op.add_column("jobs", sa.Column("document_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "jobs", "documents", ["document_id"], ["document_id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "jobs", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_column("jobs", "document_id")
    op.drop_column("jobs", "job_type")
    # ### end Alembic commands ###
