"""add statement id to receipt

Revision ID: 1d34142955a7
Revises: 0ae530f56734
Create Date: 2026-03-02 10:09:28.791632

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d34142955a7"
down_revision: Union[str, Sequence[str], None] = "0ae530f56734"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("receipts", sa.Column("statement_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None,
        "receipts",
        "bank_statements",
        ["statement_id"],
        ["statement_id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "receipts", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_column("receipts", "statement_id")
    # ### end Alembic commands ###
