"""update_user_role_to_enum

Revision ID: 2c5b27948a37
Revises: acbd5f23fffe
Create Date: 2026-02-13 18:05:48.682263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c5b27948a37'
down_revision: Union[str, Sequence[str], None] = 'acbd5f23fffe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('admin', 'developer', 'viewer', name='user_role_enum', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('admin', 'developer', 'viewer', name='user_role_enum', native_enum=False),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    # ### end Alembic commands ###
