"""add job and reconciliation match table

Revision ID: 6c1ac4325d72
Revises: e6f7a8b9c0d1
Create Date: 2026-03-01 15:35:24.876059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c1ac4325d72'
down_revision: Union[str, Sequence[str], None] = 'e6f7a8b9c0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('job_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'reconciling', 'completed', 'failed', name='job_status_enum', native_enum=False), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('reconciliation_matches',
    sa.Column('match_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('reconciliation_ref', sa.String(length=255), nullable=True),
    sa.Column('match_type', sa.Enum('unmatched', 'perfect_matched', 'bundle_matched', 'manual', name='reconciliation_match_status_enum', native_enum=False), nullable=False),
    sa.Column('matched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['line_id'], ['bank_statement_lines.line_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.receipt_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('match_id'),
    sa.UniqueConstraint('line_id', 'receipt_id', name='uq_reconciliation_line_receipt')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reconciliation_matches')
    op.drop_table('jobs')
    # ### end Alembic commands ###
