"""add updated at to account book member table

Revision ID: 7bd975efab2b
Revises: 1d34142955a7
Create Date: 2026-03-02 16:59:38.844433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bd975efab2b'
down_revision: Union[str, Sequence[str], None] = '1d34142955a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_book_members', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_account_books_deleted_at'), 'account_books', ['deleted_at'], unique=False)
    op.add_column('bank_statements', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_documents_deleted_at'), 'documents', ['deleted_at'], unique=False)
    op.add_column('jobs', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('reconciliation_matches', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reconciliation_matches', 'updated_at')
    op.drop_column('jobs', 'updated_at')
    op.drop_index(op.f('ix_documents_deleted_at'), table_name='documents')
    op.drop_column('bank_statements', 'updated_at')
    op.drop_index(op.f('ix_account_books_deleted_at'), table_name='account_books')
    op.drop_column('account_book_members', 'updated_at')
    # ### end Alembic commands ###
