"""schemas changes pt1

Revision ID: a79537ee551d
Revises: 2c5b27948a37
Create Date: 2026-02-18 14:49:29.699526

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a79537ee551d"
down_revision: Union[str, Sequence[str], None] = "2c5b27948a37"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bank_statement_lines",
        sa.Column("vendor", sa.String(length=255), nullable=False),
    )
    op.alter_column(
        "bank_statement_lines",
        "match_status",
        existing_type=sa.VARCHAR(length=9),
        type_=sa.Enum(
            "unmatched",
            "perfect_matched",
            "bundle_matched",
            "manual",
            name="statement_line_match_status_enum",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    op.drop_column("bank_statements", "account_holder")
    op.alter_column(
        "receipts",
        "match_status",
        existing_type=sa.VARCHAR(length=9),
        type_=sa.Enum(
            "unmatched",
            "perfect_matched",
            "bundle_matched",
            "manual",
            name="receipt_match_status_enum",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    op.drop_column("receipts", "billing_to_name")
    op.drop_column("receipts", "account_charged_last4")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "receipts",
        sa.Column(
            "account_charged_last4",
            sa.VARCHAR(length=4),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "receipts",
        sa.Column(
            "billing_to_name",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column(
        "receipts",
        "match_status",
        existing_type=sa.Enum(
            "unmatched",
            "perfect_matched",
            "bundle_matched",
            "manual",
            name="receipt_match_status_enum",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=9),
        existing_nullable=False,
    )
    op.add_column(
        "bank_statements",
        sa.Column(
            "account_holder",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column(
        "bank_statement_lines",
        "match_status",
        existing_type=sa.Enum(
            "unmatched",
            "perfect_matched",
            "bundle_matched",
            "manual",
            name="statement_line_match_status_enum",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=9),
        existing_nullable=False,
    )
    op.drop_column("bank_statement_lines", "vendor")
    # ### end Alembic commands ###
