"""real_initial_schema

Revision ID: acbd5f23fffe
Revises:
Create Date: 2026-02-13 17:55:02.831181

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "acbd5f23fffe"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "admin", "manager", "viewer", name="user_role_enum", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "bank_statements",
        sa.Column("statement_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("account_holder", sa.String(length=255), nullable=False),
        sa.Column("account_number_last4", sa.String(length=4), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column(
            "currency", sa.String(length=3), server_default="USD", nullable=False
        ),
        sa.Column("file_path", sa.String(length=255), nullable=False),
        sa.Column("uploaded_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"], ["users.user_id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("statement_id"),
    )
    op.create_table(
        "receipts",
        sa.Column("receipt_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("vendor", sa.String(length=255), nullable=False),
        sa.Column("invoice_number", sa.String(length=255), nullable=True),
        sa.Column("billing_date", sa.Date(), nullable=False),
        sa.Column("charged_amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("billing_to_name", sa.String(length=255), nullable=False),
        sa.Column("account_charged_last4", sa.String(length=4), nullable=False),
        sa.Column(
            "currency", sa.String(length=3), server_default="USD", nullable=False
        ),
        sa.Column("file_path", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("expense_type", sa.String(length=255), nullable=True),
        sa.Column(
            "match_status",
            sa.Enum(
                "unmatched",
                "matched",
                "manual",
                name="receipt_match_status_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("uploaded_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"], ["users.user_id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("receipt_id"),
    )
    op.create_table(
        "bank_statement_lines",
        sa.Column("line_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("statement_id", sa.Integer(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("reference_number", sa.String(length=255), nullable=False),
        sa.Column("transaction_date", sa.Date(), nullable=False),
        sa.Column("posting_date", sa.Date(), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=False),
        sa.Column("mcc", sa.String(length=10), nullable=True),
        sa.Column("charge", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column(
            "currency", sa.String(length=3), server_default="USD", nullable=False
        ),
        sa.Column(
            "match_status",
            sa.Enum(
                "unmatched",
                "matched",
                "manual",
                name="statement_line_match_status_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["statement_id"], ["bank_statements.statement_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("line_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bank_statement_lines")
    op.drop_table("receipts")
    op.drop_table("bank_statements")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
