"""add statement archival support

Revision ID: dee05f375975
Revises: f8a9b0c1d2e3
Create Date: 2026-03-26 18:52:03.831678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dee05f375975'
down_revision: Union[str, Sequence[str], None] = 'f8a9b0c1d2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_books', sa.Column('archive_after_months', sa.Integer(), server_default='18', nullable=False))
    op.add_column('bank_statements', sa.Column('status', sa.Enum('active', 'archived', name='statement_status_enum', native_enum=False), server_default='active', nullable=False))
    op.add_column('bank_statements', sa.Column('archived_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_bank_statements_status'), 'bank_statements', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_statements_status'), table_name='bank_statements')
    op.drop_column('bank_statements', 'archived_at')
    op.drop_column('bank_statements', 'status')
    op.drop_column('account_books', 'archive_after_months')
    # ### end Alembic commands ###
