"""schemas change pt2

Revision ID: f5e2e37ee399
Revises: 864932e3b3cb
Create Date: 2026-02-22 14:15:09.799808

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f5e2e37ee399"
down_revision: Union[str, Sequence[str], None] = "864932e3b3cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_books",
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("bank_name", sa.String(length=100), nullable=False),
        sa.Column("account_name", sa.String(length=100), nullable=False),
        sa.Column(
            "account_type",
            sa.Enum("checking", "credit_card", name="accounttype"),
            nullable=False,
        ),
        sa.Column(
            "currency", sa.String(length=3), server_default="USD", nullable=False
        ),
        sa.Column("account_number_last4", sa.String(length=4), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("account_id"),
    )
    op.create_table(
        "documents",
        sa.Column("document_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uploaded_by", sa.Integer(), nullable=True),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column(
            "document_type",
            sa.Enum(
                "receipt",
                "bank_statement",
                name="document_type_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("s3_key", sa.String(length=512), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending_upload",
                "pending_processing",
                "processing",
                "parsed",
                "failed",
                name="document_status_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.Column("receipt_id", sa.Integer(), nullable=True),
        sa.Column("statement_id", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["receipt_id"], ["receipts.receipt_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["statement_id"], ["bank_statements.statement_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"], ["users.user_id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("document_id"),
        sa.UniqueConstraint("receipt_id"),
        sa.UniqueConstraint("s3_key"),
        sa.UniqueConstraint("statement_id"),
    )
    op.add_column(
        "bank_statements", sa.Column("account_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint(
        op.f("bank_statements_uploaded_by_fkey"), "bank_statements", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "bank_statements", "account_books", ["account_id"], ["account_id"]
    )
    op.drop_column("bank_statements", "file_path")
    op.drop_column("bank_statements", "uploaded_by")
    op.drop_constraint(
        op.f("receipts_uploaded_by_fkey"), "receipts", type_="foreignkey"
    )
    op.drop_column("receipts", "file_path")
    op.drop_column("receipts", "uploaded_by")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "receipts",
        sa.Column("uploaded_by", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "receipts",
        sa.Column(
            "file_path", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        op.f("receipts_uploaded_by_fkey"),
        "receipts",
        "users",
        ["uploaded_by"],
        ["user_id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "bank_statements",
        sa.Column("uploaded_by", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "bank_statements",
        sa.Column(
            "file_path", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "bank_statements", type_="foreignkey")  # type: ignore[arg-type]
    op.create_foreign_key(
        op.f("bank_statements_uploaded_by_fkey"),
        "bank_statements",
        "users",
        ["uploaded_by"],
        ["user_id"],
        ondelete="SET NULL",
    )
    op.drop_column("bank_statements", "account_id")
    op.drop_table("documents")
    op.drop_table("account_books")
    # ### end Alembic commands ###
